### ISSUE TITLE
Is there an vscode extension we can use for syntax highlighing in html templates?

### ISSUE THREAD

**Issue by Pika-Pool** [beforesemicolon/cwco#15]
![Screenshot](https://user-images.githubusercontent.com/33688622/149894194-c5048e2a-6f2f-42ee-ad14-634f11e09953.png)

Right now it looks like a simple string. it'll be much better if we could get some syntax highlighting and ability to check/format the html and css in template string. Something like what the [lit-html vscode extension](https://github.com/mjbvz/vscode-lit-html) does

**Comment by ECorreia45** [comment]
Not yet (working on it).

However, you can use [inline-html](https://github.com/pushqrdx/vscode-inline-html) or even the `lit-html` one and do the following in the code;

```js
// html.js
export const html = x => x;

// my-button.ts
import {html} from './utils/html';

class MyButton extends WebComponent {
  get template() {
    return html`<button><slot></slot></button>`[0];
  }

  get stylesheet() {
    return html`<style>button {color: #900}</style>`[0];
  }
}
```

I know this is a hacky way but that is the best I can suggest for now.

I created a feature request for this #16
https://github.com/beforesemicolon/cwco/issues/16

**Comment by Pika-Pool** [comment]
The hack doesn't work as intended. The `html` function will return an array of type `TemplateStringsArray`, and not the string. This is my solution:

```typescript
function html(strings: TemplateStringsArray, ...values: any[]) {
	return strings.reduce((res, currString, currIndex) => {
		console.log(currString, ' ', currIndex);
		return res + currString + (values[currIndex] ?? '').toString();
	}, '');
}
```
