### ISSUE TITLE
Syntax highlighting support for css

### ISSUE THREAD

**Issue by hilmia** [beforesemicolon/cwco#30]
Syntax highlighting for html works, when using it with css the component doesn't work

<img width="432" alt="Screenshot 2022-09-23 at 01 21 54" src="https://user-images.githubusercontent.com/69205098/191867952-d6d684bb-4c4b-4ccd-82ca-e232eb22a890.png">

**Comment by ECorreia45** [comment]
cwco at the moment is not expecting that users will use `css` for stylesheet. Marking this as feature request.

Meanwhile id suggest you wrapping it in `style` tag instead of "css`...`" or use CSS as object: https://cwco.io/documentation/stylesheet#css-object

Thanks for this submission

**Comment by ECorreia45** [comment]
Please check the README: https://github.com/beforesemicolon/cwco#vscode

```ts
import {html, WebComponent} from "./cwco";

class MyButton extends WebComponent {
  get template() {
    return html`<button><slot></slot></button>`
  }
  
  get stylesheet() {
    return html`<style>button {color: #222}</style>`
  }
}
```

**Comment by ECorreia45** [comment]
Id also suggest trying CSS as JSON for even more powerful CSS features like nesting:

```ts
get stylesheet() {
   return {
       ".chartbuttondiv": {
           position: "absolute",
           zIndex: 2,
           ".chartbutton": {
                color" "#8e95ab",
                "&:hover": {
                     color: "#f2f2f2"
                }
           }
       }
   }
}
```
